### PR TITLE
Add needed batteries to React app

### LINKED ISSUE #4: [FEATURE] Setting up React application
**What Functionality would you like to add or fix?**
## Setting up React application

**Describe this Functionality/fix**
Will be adding the following functionalities:
- Set up basic routing with [React-Router](https://reactrouter.com/)
- Set up [Redux](https://react-redux.js.org/):
   - Redux middleware ([thunks](https://github.com/reduxjs/redux-thunk) and [logger](https://www.npmjs.com/package/redux-logger) for development)
   - Redux Store and Global State
   - Reducers and Root Reducer
   - Selectors (see [reselect](https://github.com/reduxjs/reselect))
- Set up eslint
- Create global [axios](https://github.com/axios/axios) instance for making http requests within the client
- Set up [enzyme](https://enzymejs.github.io/enzyme/) for snapshot testing

### PR DESCRIPTION
**Pull request by c12i**
# Description

Resolve #4 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas TODO
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by c12i — COMMENTED** [review]
The current pages in `src/pages` are simple placeholder components for the purposes of testing out routing, we will be adding more and building upon them as we go on. Also, if I missed any eslint and prettier options, please let me know

**Review by Clish254 — APPROVED** [review]
This looks good, make sure you clarify anything you think might raise questions to the frontend guys since almost everyone is a beginner in React

**Comment by c12i** [comment]
> This looks good, make sure you clarify anything you think might raise questions to the frontend guys since almost everyone is a beginner in React

Will be adding documentation to clarify any parts anyone will be uncertain of. Also going to post some useful resources to help better understand how some of the tools and design patterns work, particularly Redux, will post that to slack

**Comment by Clish254** [comment]
> > This looks good, make sure you clarify anything you think might raise questions to the frontend guys since almost everyone is a beginner in React
> 
> Will be adding documentation to clarify any parts anyone will be uncertain of. Also going to post some useful resources to help better understand how some of the tools and design patterns have been used, particularly Redux, will post that to slack

Great

**Review by Esther-Wavinya — COMMENTED** [review]
This is great.  I forgot to tell you to add JWT but you included. Can be merged now

**Review by Esther-Wavinya — APPROVED** [review]

**Comment by Esther-Wavinya** [comment]
#4 #5

**Comment by c12i** [comment]
You closed the pr @Esther-Wavinya 👀?

**Pull request merged**
